AllCops:
  Exclude:
    - presentations/**/*
    - templates/partials/nginx.conf/wordpress.rb
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true

Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
